import Head from "./head";
import "./globals.css";
import './fanta.css';
import AuthProvider from "@/context/AuthContext";
export const metadata = {
  title: "pyar note",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <AuthProvider>

     
      <body >
        <div id="app"> {children} </div>
        <div id="portal"></div>
        
      </body>
       </AuthProvider>
    </html>
  );
}
